#include "SurfaceMesh.hh"
#include <ignition/gazebo/System.hh>
#include <ignition/gazebo/Model.hh>
#include <ignition/gazebo/Link.hh>
#include <ignition/gazebo/Joint.hh>
#include <ignition/gazebo/Util.hh>
#include <ignition/gazebo/components/Name.hh>
#include <ignition/gazebo/components/Model.hh>
#include <ignition/gazebo/components/ParentEntity.hh>
#include <ignition/gazebo/components/ContactSensorData.hh>
#include <ignition/common/Console.hh>
#include <ignition/plugin/Register.hh>
#include <cstdlib>
#include <filesystem>
#include <iomanip>

namespace magnetic_robot {
namespace sim=ignition::gazebo;
class MagneticAdhesion : public sim::System,public sim::ISystemConfigure,
                         public sim::ISystemPreUpdate,public sim::ISystemPostUpdate {
  struct Target {std::string name;SurfaceMesh mesh;sim::Entity entity=sim::kNullEntity;};
  struct Wheel {sim::Entity entity,carrier;bool active=false;double force=0,gap=1;V vector=V::Zero;};
  std::vector<Target> targets;std::vector<Wheel>wheels;
  sim::Entity robot,steering,frontJoint,rearJoint;
  double force=200,capture=.0005,release=.001;bool ready=false,projectTangential=true;
  std::ofstream csv;size_t rows=0;
 public:
  void Configure(const sim::Entity&e,const std::shared_ptr<const sdf::Element>&s,
                 sim::EntityComponentManager&ecm,sim::EventManager&) override {
    robot=e;auto model=sim::Model(e);
    // force_per_wheel is the load generated by one contacting finite face, not
    // the total per wheel: see the per-face accumulation in PreUpdate.
    force=s->Get<double>("force_per_wheel",200).first;capture=s->Get<double>("capture_gap",.0005).first;release=s->Get<double>("release_gap",.001).first;
    projectTangential=s->Get<bool>("project_tangential",true).first;
    if(force<=0||capture<0||release<capture)throw std::runtime_error("Invalid adhesion configuration");
    const char* root=std::getenv("MAGNETIC_ROBOT_RESOURCE_ROOT");
    if(!root)throw std::runtime_error("MAGNETIC_ROBOT_RESOURCE_ROOT is required; use gazebo_robot/run.sh");
    auto add=[&](const std::string&name,const std::string&file){Target t;t.name=name;t.mesh.Load((std::filesystem::path(root)/file).string());targets.push_back(std::move(t));};
    if(s->HasElement("surface")){
      auto elem=s->FindElement("surface");while(elem){add(elem->Get<std::string>("model"),elem->Get<std::string>("file"));elem=elem->GetNextElement("surface");}
    }else add(s->Get<std::string>("default_surface_model"),s->Get<std::string>("default_surface_file"));
    for(auto name:{"front","rear"}) {
      std::string prefix=name;
      auto wheel=model.LinkByName(ecm,prefix+"_wheel_link");
      auto carrier=model.LinkByName(ecm,prefix=="front"?"front_steering_link":"base_link");
      if(wheel==sim::kNullEntity||carrier==sim::kNullEntity)throw std::runtime_error("Missing wheel or carrier link");
      wheels.push_back({wheel,carrier});
    }
    steering=model.JointByName(ecm,"front_steering_joint");frontJoint=model.JointByName(ecm,"front_wheel_joint");rearJoint=model.JointByName(ecm,"rear_wheel_joint");
    for(auto joint:{steering,frontJoint,rearJoint})sim::Joint(joint).EnablePositionCheck(ecm);
    if(const char*path=std::getenv("MAGNETIC_ROBOT_DIAGNOSTICS")){
      csv.open(path);if(!csv)throw std::runtime_error("Cannot write diagnostics");
      csv<<"time,steer,front_angle,rear_angle,x,y,z,roll,pitch,yaw,front_force,rear_force,front_gap,rear_gap,front_fx,front_fy,front_fz,rear_fx,rear_fy,rear_fz,contacts\n"<<std::setprecision(12);
    }
    ignmsg<<"MagneticAdhesion configured: "<<force<<" N per wheel, "<<targets.size()<<" finite surface set(s).\n";
  }
  void PreUpdate(const sim::UpdateInfo&info,sim::EntityComponentManager&ecm) override {
    if(info.paused)return;
    if(!ready){
      for(auto &t:targets){
        if(t.name=="__no_magnetic_target__")continue;
        t.entity=ecm.EntityByComponents(sim::components::Model(),sim::components::Name(t.name));
        if(t.entity==sim::kNullEntity)throw std::runtime_error("Magnetic target model not found: "+t.name);
      }
      ready=true;
    }
    if(info.dt<=decltype(info.dt)::zero()){
      for(auto&w:wheels){w.active=false;w.force=0;w.vector=V::Zero;}
      return;
    }
    for(size_t wi=0;wi<wheels.size();++wi){
      auto &w=wheels[wi];auto wp=sim::worldPose(w.entity,ecm),cp=sim::worldPose(w.carrier,ecm);
      // Carrier normal and wheel axle are invariant under wheel spin.
      const V axle=wp.Rot().RotateVector(V::UnitY).Normalized();
      const V down=cp.Rot().RotateVector(-V::UnitZ).Normalized();
      const double limit=.0315+(w.active?release:capture);
      // Each finite contact face generates its own force_per_wheel load. At a
      // concave corner (plate root, 90 deg internal edge) a wheel can contact
      // two faces at once and therefore receives 2 * force_per_wheel.
      struct Sample {V point,normal,contact,axle;double gap;size_t target;};
      std::vector<Sample> samples;
      w.force=0;w.vector=V::Zero;w.gap=1;
      // Ray basis: probe is the nominal surface normal (-down) of the face the
      // carrier currently stands on; tanv is the in-plane perpendicular. The
      // fan sweeps the radial plane about probe.
      V n=(-down);n-=(n.Dot(axle))*axle;n.Normalize();
      V tanv=axle.Cross(n).Normalized();
      const V probe=-n;
      // Rays start at the WHEEL CENTRE, not on the rim: a rim probe sits inside
      // the material for a tilted ray, so a concave corner's second face would
      // always be missed. Contact is decided by the perpendicular centre-to-face
      // distance (points inside the wheel iff that distance is <= R), so the fan
      // only has to sweep the radial half-plane that can face the steel.
      constexpr int kFanCount=13;
      for(double localY:{-.014,-.006,0.0,.006,.014}){
        double y=wi==0?localY:-localY;V origin=wp.Pos()+axle*y;
        for(int fi=0;fi<kFanCount;++fi){
          const double a=-M_PI/2.0+M_PI*fi/(kFanCount-1);
          V dir=probe*std::cos(a)+tanv*std::sin(a);
          dir.Normalize();
          // Query every candidate face independently. Sharing one running best
          // distance here let a nearer face veto a farther valid one, so at a
          // corner the wheel could report zero adhesion even though another
          // face was in range and correctly oriented.
          for(size_t ti=0;ti<targets.size();++ti){
            const auto &t=targets[ti];
            if(t.entity==sim::kNullEntity)continue;
            auto tp=sim::worldPose(t.entity,ecm);
            V localOrigin=tp.Rot().RotateVectorReverse(origin-tp.Pos());
            V localDir=tp.Rot().RotateVectorReverse(dir);
            auto h=t.mesh.Ray(localOrigin,localDir,limit);
            if(h.normal.Length()==0)continue;
            V normal=tp.Rot().RotateVector(h.normal);
            V point=tp.Pos()+tp.Rot().RotateVector(h.point);
            // Only the wheel's own sidewalls are excluded. The old extra test
            // (normal.(-down) > 0.7) described "the surface the carrier is
            // currently standing on", which discarded the second face of every
            // concave corner -- exactly the load the model is supposed to add.
            if(std::abs(normal.Dot(axle))>.35)continue;
            // Perpendicular centre-to-face distance. A face is in contact iff
            // the point of the wheel nearest it is within R, and sharing one
            // running best distance across faces let a nearer face veto a
            // farther valid one, so each face is queried independently.
            const double gap=(point-wp.Pos()).Dot(-normal)-.0315;
            if(gap<-.002||gap>limit-.0315)continue;
            // Force application point is the foot of the perpendicular from the
            // wheel centre onto the face, i.e. the point of the wheel nearest
            // that face -- NOT the ray hit point. For an oblique ray the hit
            // point is laterally offset from that foot, so using it makes the
            // force line miss the wheel centre and injects a spurious moment
            // about the axle. The foot lies at centre + normal * (R + gap),
            // which is exactly the same perpendicular distance the contact test
            // above uses, so contact decision and force application stay
            // consistent.
            const V contact=wp.Pos()+normal*(.0315+gap);
            samples.push_back({wp.Pos(),normal,contact,axle,gap,ti});
          }
        }
      }
      w.active=!samples.empty();if(!w.active)continue;
      // Keep samples contiguous per contacting face so each face collapses to
      // exactly one force_per_wheel, shared among its own samples for the
      // moment calculation.
      std::vector<size_t> order(samples.size());
      for(size_t i=0;i<order.size();++i)order[i]=i;
      std::stable_sort(order.begin(),order.end(),
                       [&](size_t a,size_t b){return samples[a].target<samples[b].target;});
      for(size_t b=0;b<order.size();){
        const size_t target=samples[order[b]].target;size_t e=b;
        while(e<order.size()&&samples[order[e]].target==target)++e;
        const double share=force/static_cast<double>(e-b);
        for(size_t k=b;k<e;++k){
          const auto &s=samples[order[k]];
          V f=-s.normal*share;
          // Method 1: adhesion must hold the wheel onto the steel, never drag it
          // along the surface. The rolling direction is the line perpendicular
          // to both the axle and this face normal, i.e. the tangent the wheel
          // travels along while in contact with this face. Any component of the
          // magnet load along it is pure parasitic drag that the drive has to
          // overcome (measured: drive 203 N vs 200 N per face -> stall), so it
          // is projected out and the remaining normal component is rescaled to
          // keep the full force_per_wheel load. The result stays perpendicular
          // to the rolling direction, so the wheel's rotational freedom is
          // untouched and the plain rolling behaviour the test suite checks is
          // preserved exactly. At a single contact the normal is already
          // perpendicular to the tangent, so this is a no-op; it only bites for
          // the oblique/curved-face samples where the ray normal is a poor
          // approximation of the radial contact normal.
          if(projectTangential){
            const V tangent=s.axle.Cross(s.normal);
            const double t2=tangent.SquaredLength();
            if(t2>1e-12){
              const V unit=tangent/std::sqrt(t2);
              const V perp=f-unit*f.Dot(unit);
              const double p2=perp.SquaredLength();
              if(p2>1e-12)f=perp*(f.Length()/std::sqrt(p2));
            }
          }
          // Fortress AddWorldForce silently does nothing without an opt-in
          // WorldPose component, and its offset is COM-relative. Compute the
          // world wrench about the link origin explicitly to avoid ambiguity.
          // The force acts at the perpendicular foot on the wheel rim, so its
          // line of action passes through the wheel centre and the moment about
          // that centre is zero.
          sim::Link(w.entity).AddWorldWrench(ecm,f,(s.contact-wp.Pos()).Cross(f));
          w.vector+=f;
        }
        b=e;
      }
      // w.gap must reflect the closest face, not whichever sample was pushed
      // first, so recompute it from the accepted samples.
      for(const auto &s:samples)w.gap=std::min(w.gap,s.gap);
      w.force=w.vector.Length();
    }
  }
  void PostUpdate(const sim::UpdateInfo&info,const sim::EntityComponentManager&ecm) override {
    if(info.paused||!csv)return;
    auto position=[&](sim::Entity e){auto p=sim::Joint(e).Position(ecm);return p&&!p->empty()?p->at(0):0.;};
    auto p=sim::worldPose(sim::Model(robot).LinkByName(ecm,"base_link"),ecm);auto r=p.Rot().Euler();
    int contacts=0;
    ecm.Each<sim::components::ContactSensorData,sim::components::ParentEntity>([&](const sim::Entity&,const auto*c,const auto*parent){for(auto&w:wheels)if(parent->Data()==w.entity)contacts+=c->Data().contact_size();return true;});
    csv<<std::chrono::duration<double>(info.simTime).count()<<','<<position(steering)<<','<<position(frontJoint)<<','<<position(rearJoint)<<','<<p.Pos().X()<<','<<p.Pos().Y()<<','<<p.Pos().Z()<<','<<r.X()<<','<<r.Y()<<','<<r.Z();
    for(auto&w:wheels)csv<<','<<w.force;
    for(auto&w:wheels)csv<<','<<w.gap;
    for(auto&w:wheels)csv<<','<<w.vector.X()<<','<<w.vector.Y()<<','<<w.vector.Z();
    csv<<','<<contacts<<'\n';if(++rows%1000==0)csv.flush();
  }
};
}
IGNITION_ADD_PLUGIN(magnetic_robot::MagneticAdhesion,ignition::gazebo::System,
 magnetic_robot::MagneticAdhesion::ISystemConfigure,
 magnetic_robot::MagneticAdhesion::ISystemPreUpdate,
 magnetic_robot::MagneticAdhesion::ISystemPostUpdate)
